django/solonotebooks/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

handler500 = 'solonotebooks.cotizador.views.index'
handler404 = 'solonotebooks.cotizador.views.index'

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DOC_ROOT}),
    (r'^admin/', include(admin.site.urls)))

urlpatterns += patterns('solonotebooks.cotizador.views_notebooks',
    (r'^notebooks/processor_lines/(?P<processor_line_id>\d+)/$', 'processor_line_details'),
    (r'^notebooks/processor_lines/$', 'processor_line'),
    (r'^notebooks/video_card_lines/(?P<video_card_line_id>\d+)/$', 'video_card_line_details'),
    (r'^notebooks/video_card_lines/$', 'video_card_line'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_videocards',
    (r'^video_cards/gpu_details/(?P<gpu_id>\d+)/$', 'gpu_details'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_cellphones',
    (r'^cellphones/plans/(?P<plan_id>\d+)/$', 'plan_details'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_account',
    (r'^account/facebook_login/$', 'facebook_login'),
    (r'^account/facebook_fusion/$', 'facebook_fusion'),
    (r'^account/facebook_ajax_login/$', 'facebook_ajax_login'),
    (r'^account/login/$', 'login'),
    (r'^account/logout/$', 'logout'),
    (r'^account/validate_email/$', 'validate_email'),
    (r'^account/fuse_facebook_account/$', 'fuse_facebook_account'),
    (r'^account/request_password_regeneration/$', 'request_password_regeneration'),
    (r'^account/regenerate_password/$', 'regenerate_password'),
    (r'^account/subscriptions/$', 'subscriptions'),
    (r'^account/$', 'subscriptions'),
    (r'^account/change_email/$', 'change_email'),
    (r'^account/change_password/$', 'change_password'),
    (r'^account/send_confirmation_mail/$', 'send_confirmation_mail'),    
    (r'^account/add_subscription/$', 'add_subscription'),
    (r'^account/enable_subscription_mail/(?P<subscription_id>\d+)$', 'enable_subscription_mail'),
    (r'^account/disable_subscription_mail/(?P<subscription_id>\d+)$', 'disable_subscription_mail'),    
    (r'^account/remove_subscription/(?P<subscription_id>\d+)/$', 'remove_subscription'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_store',
    (r'^store/$', 'index'),
    (r'^store/registry/$', 'registry'),
    (r'^store/entities/(?P<shpe_id>\d+)/$', 'entity_details'),
    (r'^store/entities/(?P<shpe_id>\d+)/refresh_price/$', 'entity_refresh_price'),
    (r'^store/advertisement/$', 'advertisement'),
    (r'^store/advertisement/reserve_slots/$', 'reserve_slots'),
    (r'^store/advertisement/free_slots/$', 'free_slots'),
    (r'^store/statistics/$', 'statistics'),
    (r'^store/update_prices/$', 'update_prices'),
    (r'^store/competition_report/$', 'competition_report'),
    (r'^store/competition_report/excel$', 'competition_report_excel'),
    (r'^store/sponsored_results/$', 'sponsored_results'),
    (r'^store/advertisement_results/$', 'advertisement_results')
)

urlpatterns += patterns('solonotebooks.cotizador.views_manager',
    (r'^manager/$', 'news'),
    (r'^manager/news/$', 'news'),
    (r'^manager/analyze_searches$', 'analyze_searches'),
    (r'^manager/statistics$', 'statistics'),  
    (r'^manager/stores/$', 'stores'),
    (r'^manager/stores/(?P<store_id>\d+)$', 'store_details'),
    (r'^manager/stores/(?P<store_id>\d+)/advertisement/$', 'store_advertisement'),
    (r'^manager/stores/(?P<store_id>\d+)/statistics/$', 'store_statistics'),
    (r'^manager/staff/$', 'staff'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_staff',
    (r'^staff/(?P<staff_id>\d+)/new_entities$', 'new_entities'),
    (r'^staff/(?P<staff_id>\d+)/storehasproductentity/(?P<store_has_product_entity_id>\d+)$', 'storehasproductentity_edit'),
    (r'^staff/(?P<staff_id>\d+)/storehasproductentity/(?P<store_has_product_entity_id>\d+)/hide$', 'storehasproductentity_hide'),
    (r'^staff/(?P<staff_id>\d+)/storehasproductentity/(?P<store_has_product_entity_id>\d+)/show$', 'storehasproductentity_show'),
    (r'^staff/(?P<staff_id>\d+)/storehasproductentity/(?P<store_has_product_entity_id>\d+)/refresh_price$', 'storehasproductentity_refresh_price'),
    (r'^staff/(?P<staff_id>\d+)/polymorphic_admin_request/(?P<product_id>\d+)$', 'polymorphic_admin_request'),
    (r'^staff/(?P<staff_id>\d+)/clone_product/(?P<product_id>\d+)$', 'clone_product'),
    (r'^staff/(?P<staff_id>\d+)/storehasproductentity/(?P<store_has_product_entity_id>\d+)/change_ptype$', 'storehasproductentity_change_ptype'),
    (r'^staff/(?P<staff_id>\d+)/statistics$', 'statistics'),  
    (r'^staff/(?P<staff_id>\d+)/registry$', 'registry'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_legacy',
    (r'^notebooks/(?P<notebook_id>\d+)/$', 'notebook_details'),
    (r'^processor_line_families/(?P<processor_line_family_id>\d+)/$', 'processor_line_family_details'),
    (r'^processor_line_families/$', 'all_processor_line_families'),
    (r'^video_card_line/(?P<video_card_line_id>\d+)/$', 'video_card_line_details'),
    (r'^video_card_line/$', 'video_card_line'),
    (r'^store_notebook/(?P<store_notebook_id>\d+)/$', 'store_notebook_redirect'),
    )
 
urlpatterns += patterns('solonotebooks.cotizador.views_services',
    (r'^products/(?P<product_id>\d+)/details/$', 'product_details'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_chw',
    (r'^mini/(?P<product_id>\d+)/$', 'inline_forum_post'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_hponline',
    (r'^hponline/$', 'index'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_tablet',
    (r'^tablet/$', 'index'),
)

urlpatterns += patterns('solonotebooks.cotizador.views_ripley',
    (r'^ripley/$', 'index'),
    (r'^ripley/notebooks/$', 'notebooks'),
    (r'^ripley/notebooks/(?P<notebook_id>\d+)/$', 'notebook_details'),
    (r'^ripley/notebooks/(?P<notebook_id>\d+)/json/$', 'notebook_details_json'),
)

urlpatterns += patterns('solonotebooks.cotizador.views',
    (r'^$', 'index'),
    (r'^products/(?P<product_id>\d+)/$', 'product_details_legacy'),
    (r'^products/(?P<product_url>\S+)/$', 'product_details'),
    (r'^store_product/(?P<store_product_id>\d+)/$', 'store_product_redirect'),
    (r'^sponsored_product/(?P<shp_id>\d+)/$', 'sponsored_product_redirect'),
    (r'^all_products/$', 'all_products'),
    (r'^search/$', 'search'),
    (r'^ad_visited/(?P<advertisement_id>\d+)/$', 'ad_visited'),
    (r'^ad_impressed/$', 'ad_impressed'),
    (r'^search/$', 'search'),
    (r'^(?P<product_type_urlname>\w+)/catalog/$', 'product_type_catalog'),
    (r'^(?P<product_type_urlname>\w+)/$', 'product_type_index'),
)

django/solonotebooks/cotizador/models/store.py
import os, sys, traceback
from solonotebooks.logger import Logger
from datetime import date
from django.db.models import Q
from django.db import models
from sorl.thumbnail.fields import ImageWithThumbnailsField
from solonotebooks import settings

class Store(models.Model):
    name = models.CharField(max_length = 255)
    classname = models.CharField(max_length = 255)
    url = models.URLField()
    sponsor_cap = models.IntegerField(default = 0)
    picture = ImageWithThumbnailsField(
        thumbnail = { 'size': (140, 90), },                                          
        upload_to = 'store_logos',
        generate_on_save = True,)
    affiliate_id = models.CharField(max_length=255, blank=True, null=True)
    
    def fetch_store(self):
        from solonotebooks.fetch_scripts import *
        return eval(self.classname + '()')
    
    def __unicode__(self):
        return unicode(self.name)
        
    def fetch_product_data(self, url):
        from . import StoreHasProductEntity
        from solonotebooks.fetch_scripts import *
        fetch_store = self.fetch_store()
        product = fetch_store.retrieve_product_data(url)
        if not product:
            return None
        else:
            shpes = StoreHasProductEntity.objects.filter(custom_name = product.custom_name, store = self)
            if shpes:
                return shpes[0]
            else:
                return None
        
    def save_product(self, product):
        from . import StoreHasProductEntity, LogNewEntity, ProductType
        print 'Guardando ' + str(product)
        print 'Buscando si tiene un registro existente'
        try:
            shpe = StoreHasProductEntity.objects.get(comparison_field = product.comparison_field)
            print 'Si tiene registro existente, usandolo'
        except StoreHasProductEntity.DoesNotExist:
            print 'No tiene registro existente, creandolo'
            shpe = StoreHasProductEntity()
            shpe.url = product.url
            shpe.custom_name = product.custom_name
            shpe.comparison_field = product.comparison_field
            shpe.shp = None
            shpe.is_available = True
            shpe.is_hidden = False
            shpe.latest_price = product.price
            shpe.store = self
            try:
                ptype = ProductType.objects.get(classname = product.ptype)
                shpe.ptype = ptype
            except:
                pass
            shpe.save()
            LogNewEntity.new(shpe).save()
            
        shpe.update_with_product(product)
        
    def update_products_from_webpage(self, update_shpes_on_finish = False):
        from . import LogFetchStoreError
        fetch_store = self.fetch_store()
        fetch_log_file_location = os.path.join(settings.LOG_DIRECTORY, fetch_store.__class__.__name__ + '_fetch.txt')
        logger = Logger(sys.stdout, fetch_log_file_location)
        sys.stdout = logger
        
        try:
            store = Store.objects.get(name = fetch_store.name)
        except Store.DoesNotExist:
            store = Store()
            store.name = fetch_store.name
            store.save()
            
        store.set_shpe_prevent_availability_change_flag(False)
            
        try:
            if update_shpes_on_finish:
                for shpe in store.storehasproductentity_set.all():
                    shpe.delete_today_history()
            
            products = fetch_store.get_products()        
            
            update_log_file_location = os.path.join(settings.LOG_DIRECTORY, fetch_store.__class__.__name__ + '_update.txt')
            print update_log_file_location
            logger.change_log_file(update_log_file_location)
            for product in products:
                self.save_product(product)
            
            if update_shpes_on_finish:
                from . import ProductVisit
                product_visits = ProductVisit.get_last_day_visitor_count_for_each_product()

                for shpe in store.storehasproductentity_set.all():
                    shpe.update(recursive=True, product_visits=product_visits)

            try:                
                log_error = LogFetchStoreError.objects.get(log_entry__date = date.today(), store = store)
                log_error.delete()
            except LogFetchStoreError.DoesNotExist, e:
                pass
                
        except Exception, e:
            traceback.print_exc(file=sys.stdout)
            print e
            print('Error al obtener los productos de ' + store.name)
            
            try:                
                log_error = LogFetchStoreError.objects.get(log_entry__date = date.today(), store = store)
            except LogFetchStoreError.DoesNotExist, ex:
                LogFetchStoreError.new(store, str(e))
            
            store.set_shpe_prevent_availability_change_flag(True)
            
        sys.stdout = logger.default_stdout()
        
    def set_shpe_prevent_availability_change_flag(self, flag):
        from . import StoreHasProductEntity
        shpes = StoreHasProductEntity.objects.filter(store = self)
        for shpe in shpes:
            shpe.prevent_availability_change = flag
            shpe.save()
            
    def get_products_in_category(self, ptype, ordering):
        from . import StoreHasProductEntity, StoreHasProduct
        classname = ptype.get_class()
        products = classname.get_available()
        
        shps = StoreHasProduct.objects.filter(shpe__store = self, product__in = products)
        
        if ordering == '1':
            shps = shps.order_by('product__display_name')
        elif ordering == '2':
            shps = shps.order_by('-product__week_visitor_count')
        elif ordering == '3':
            shps = shps.order_by('-product__week_external_visits')
        
        final_products = []    
        for shp in shps:
            shp.product.store_shpe = shp.shpe
            
            other_shps = StoreHasProduct.objects.filter(product = shp.product, shpe__isnull=False).filter(~Q(shpe__store = self)).order_by('shpe__latest_price')
            if other_shps:
                shp.product.competitor_shps = other_shps[:3]
            else:
                shp.product.competitor_shps = []
                
            final_products.append(shp.product)
            
        return final_products
    
    class Meta:
        ordering = ['name']
        app_label = 'cotizador'
        verbose_name = 'Store'

django/solonotebooks/cotizador/forms/store_has_product_entity_edit_form.py
#-*- coding: UTF-8 -*-
from django import forms
from django.forms.util import ErrorList
from solonotebooks.cotizador.models import Store, Product

class StoreHasProductEntityEditForm(forms.Form):
    product = forms.ModelChoiceField(queryset = Product.objects.all())

django/templates/manager/analyze_searches.html
{% extends "manager/base.html" %}

{% block title %}Analizador de consultas - {{ site_name }}{% endblock %}

{% block manager_content %}

<h1>Analizador de consultas</h1>
{% for key, value in results.items %}
    {% if value.meta.is_available %}
        <h3>{{ key.name }} ({{ value.meta.percentage|floatformat }} %)</h3>
        {% for subkey, subvalue in value.data.items %}
            <i>{{ subkey }}:</i> {{ subvalue.0 }} ({{ subvalue.1|floatformat }}%)<br />
        {% endfor %}
    <img src="/media/pics/temp/{{ key.name }}-{{num_queries}}.png" />
    {% endif %}    
{% endfor %}

{% endblock %}

django/templates/manager/base.html
{% extends "base_generic.html" %}

{% block content %}
{% block manager_content %}
{% endblock %}
{% endblock %}

django/templates/manager/base_store.html
{% extends "manager/base.html" %}

{% block manager_content %}

<div id="account_options">
    <a href="{% url solonotebooks.cotizador.views_manager.store_details store.id %}" title="Registros"><span>Registros</span></a>
     | 
    <a href="{% url solonotebooks.cotizador.views_manager.store_advertisement store.id %}" title="Gestor de publicidad"><span>Gestor de publicidad</span></a>
     | 
    <a href="{% url solonotebooks.cotizador.views_manager.store_statistics store.id %}" title="Estadísticas"><span>Estadísticas</span></a>
</div>

{% block manager_store_content %}

{% endblock %}

{% endblock %}    

django/templates/manager/comments.html
{% extends "manager/base.html" %}

{% block title %}Comentarios - {{ site_name }}{% endblock %}

{% block manager_content %}

<h2>Comentarios sin validar</h2>

{% for comment in due_comments %}
    <strong>Fecha: </strong> {{ comment.date }}
    <br />
    <strong>Nickname: </strong> {{ comment.nickname }}
    <br />
    <strong>Producto: </strong> <a href="{% url solonotebooks.cotizador.views.product_details comment.product.url %}">{{ comment.product }}</a>
    <br />
    <strong>Comentario: </strong>
    <br />
    {{ comment.comments }}
    <br />
    <form method="POST" action="{% url solonotebooks.cotizador.views_manager.validate_comment comment.id %}">
        <input type="submit" value="Validar comentario" />
    </form>
    <form method="POST" action="{% url solonotebooks.cotizador.views_manager.delete_comment comment.id %}">
        <input type="submit" value="Eliminar comentario" />
    </form>
    <hr />

{% endfor %}


<form method="POST" action="{% url solonotebooks.cotizador.views_manager.validate_all %}">
    <input type="submit" value="Validar todos los mensajes" />
</form>
<form method="POST" action="{% url solonotebooks.cotizador.views_manager.delete_all %}">
    <input type="submit" value="Eliminar todos los mensajes" />
</form>

<h2>Últimos comentarios</h2>

{% for comment in app_comments %}
    <strong>Fecha: </strong> {{ comment.date }}
    <br />
        <strong>Nickname: </strong>     
    {% if comment.user %}
        {{ comment.user.get_profile.name }}
    {% else %}
        {{ comment.nickname }}
    {% endif %}
    <br />
    <strong>Producto: </strong> <a href="{% url solonotebooks.cotizador.views.product_details comment.product.url %}">{{ comment.product }}</a>
    <br />
    <strong>Comentario: </strong>
    <br />
    {{ comment.comments }}
    <br />
    <form method="POST" action="{% url solonotebooks.cotizador.views_manager.delete_comment comment.id %}">
        <input type="submit" value="Eliminar comentario" />
    </form>
    <hr />

{% endfor %}

{% endblock %}

django/templates/manager/news.html
{% extends "manager/base.html" %}

{% block title %}Noticias - {{ site_name }}{% endblock %}

{% block manager_content %}

<h2>Últimos eventos</h2>

{% for log in last_logs %}
    <h3>{{ log.date }}</h3>
    
    <h4>Errores de recepción</h4>
    
    {% if log.logfetchstoreerror_set.all %}    
        <ul>
            {% for log in log.logfetchstoreerror_set.all %}
                <li>{{ log.print_message }}</li>
            {% endfor %}
        </ul>
        <br />
    {% else %}
        <p>No se reportaron errores</p>
    {% endif %}
    
    <h4>Cambios de nombre</h4>
    
    {% if log.logchangeentityname_set.all %}
        <ul>
        {% for log in log.logchangeentityname_set.all %}
            <li>{{ log.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron cambios de nombre</p>
    {% endif %}
    
    <h4>Nuevas entidades</h4>
    
    {% if log.lognewentity_set.all %}
        <ul>
        {% for log_new_entity in log.lognewentity_set.all %}
            <li>{{ log_new_entity.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron nuevas entidades</p>
    {% endif %}
    
    <h4>Entidades perdidas</h4>
    
    {% if log.loglostentity_set.all %}
        <ul>
        {% for log_lost_entity in log.loglostentity_set.all %}
            <li>{{ log_lost_entity.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron pérdidas de entidades</p>
    {% endif %}
    
    <h4>Entidades resucitadas</h4>
    
    {% if log.logreviveentity_set.all %}
        <ul>
        {% for log_revive_entity in log.logreviveentity_set.all %}
            <li>{{ log_revive_entity.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron resucitaciones de entidades</p>
    {% endif %}    
    
    <h4>Entidades con cambios de precio</h4>
    
    {% if log.logchangeentityprice_set.all %}
        <ul>
        {% for log_change_entity_price in log.logchangeentityprice_set.all %}
            <li>{{ log_change_entity_price.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron cambios de precio en las entidades</p>
    {% endif %}

    <h4>Productos perdidos</h4>

    {% if log.loglostproduct_set.all %}
        <ul>
        {% for log_lost_product in log.loglostproduct_set.all %}
            <li>{{ log_lost_product.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron pérdidas de productos</p>
    {% endif %}
    
    <h4>Productos resucitados</h4>
    
    {% if log.logreviveproduct_set.all %}
        <ul>
        {% for log_revive_product in log.logreviveproduct_set.all %}
            <li>{{ log_revive_product.message|safe }}</li>
        {% endfor %}
        </ul>
        <br />
    {% else %}
        <p>No se reportaron resucitaciones de productos</p>
    {% endif %}    
    
    <h4>Productos con cambios de precio</h4>
    
    {% if log.logchangeproductprice_set.all %}
        <ul>
        {% for log_change_product_price in log.logchangeproductprice_set.all %}
            <li>{{ log_change_product_price.message|safe }}</li>
        {% endfor %}
        </ul>    
        <br />
    {% else %}
        <p>No se reportaron cambios de precio en los productos</p>
    {% endif %}
{% endfor %}

{% endblock %}

django/templates/manager/staff.html
{% extends "manager/base.html" %}

{% block title %}Registro de staff - {{ site_name }}{% endblock %}

{% block manager_content %}

<h2>Listado de staff</h2>

<ul>
{% for user in staff %}
    <li><a href="{% url solonotebooks.cotizador.views_staff.registry user.id%}">{{ user }}</a></li>
    {% endfor %}
</ul>
    
{% endblock %}

django/templates/manager/staff_details.html
{% extends "manager/base.html" %}

{% block title %}Manager de staff - {{ staff }}{% endblock %}

{% block manager_content %}

<h2>Detalles de {{ staff }}</h2>

<h3>Últimas asociaciones</h3>

<ul>
    {% for shpe in shpes %}
        <li><a href="{% url solonotebooks.cotizador.views_staff.storehasproductentity_edit user.id shpe.id %}">{{ shpe.custom_name }}</a> -> <a href="{% url solonotebooks.cotizador.views.product_details shpe.shp.product.id %}">{{ shpe.shp.product }}</a></li>        
    {% endfor %}
</ul>

<br />

<h3>Últimos productos creados</h3>
<ul>
    {% for product in products %}
            <li><a href="{% url solonotebooks.cotizador.views.product_details product.id %}">{{ product }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

django/templates/manager/statistics.html
{% extends "manager/base.html" %}

{% block title %}
    Estadísticas de {{ settings.SITE_NAME }}
{% endblock %}

{% block content %}

<form method="get" id="advertisement_slot_form">
    Desde: {{ form.start_date }} &nbsp;&nbsp;Hasta: {{ form.end_date }}
    <input type="submit" value="Actualizar" />
</form>

<div id="advertisement_tabs">
	<ul>
		<li><a href="#tabs">Entidades creadas</a></li>
		<li><a href="#tabs-2">Entidades resueltas</a></li>
		<li><a href="#tabs-3">Productos creados</a></li>
	</ul>
	<div id="tabs">
        <img src="/media/pics/charts/manager_statistics_01.png?generator={{tag}}" />
        <br />
        <strong>Número de entidades registradas en el periodo:</strong> {{ shpes_created_count }}
	</div>
	<div id="tabs-2">
        <img src="/media/pics/charts/manager_statistics_02.png?generator={{tag}}" />
        <br />
        <strong>Número de entidades resueltas en el periodo:</strong> {{ shpes_associated_count }}
	</div>
	<div id="tabs-3">
        <img src="/media/pics/charts/manager_statistics_03.png?generator={{tag}}" />
        <br />
        <strong>Número de productos creados en el periodo:</strong> {{ product_creation_count }}
	</div>
</div>
{% endblock %}

django/templates/manager/store_advertisement.html
{% extends "manager/base_store.html" %}

{% block title %}
    Gestor de publicidad de {{ store }} - {{ site_name }}
{% endblock %}

{% block manager_store_content %}

<div id="result_set">
    <h2>Gestor de publicidad de {{ store }}</h2>
    
    <div id="free_products" class="advertisement_list">
        <h4>Productos disponibles</h4>
        <form id="reserve_products_form" method="post" action="/store/advertisement/reserve_slots/">
            {% if free_products %}
                <ul>
                    {% for product_pair in free_products %}
                        <li><input type="checkbox" name="selected_products[]" value="{{ product_pair.0.id }}" /> <a href="{% url solonotebooks.cotizador.views_store.entity_details product_pair.0.shpe.id %}">{{ product_pair.1 }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No hay productos disponibles</p>
            {% endif %}
        </form>
    </div>
    
    <div id="reserved_products" class="advertisement_list">
        <h4>Productos reservados</h4>
        <form id="free_products_form" method="post" action="/store/advertisement/free_slots/">
        {% if reserved_products %}
            <ul>
                {% for product_pair in reserved_products %}
                    <li><input type="checkbox" name="selected_products[]" value="{{ product_pair.0.id }}" /> <a href="{% url solonotebooks.cotizador.views_store.entity_details product_pair.0.shpe.id %}">{{ product_pair.1 }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No hay productos reservados</p>
        {% endif %}
        </form>
        <p class="advertisement_counter">{{ reserved_products|length }} de {{ store.sponsor_cap }} lugares ocupados</p>
        <p><a href="/admin/cotizador/store/{{ store.id }}">Asignar lugares</a></p>
    </div>
    
    <div id="advertisement_buttons">
        <p><input type="button" id="reserve_button" value=">> Reservar >>" /></p>
        <p><input type="button" id="free_button" value="<< Liberar <<" /></p>
    </div>
    
    <br class="clear" />
    <br />
    <hr />
    <h4>Equipos ya tomados por otras tiendas</h4>
    {% if unavailable_products %}
        <ul>
            {% for product_pair in unavailable_products %}
                <li>{{ product_pair.1 }} 
                    (<a href ="{% url solonotebooks.cotizador.views.product_details product_pair.1.url %}">Link en {{ site_name }}</a> 
                    / 
                    <a href ="{{ product_pair.0.shpe.url }}"> Link en {{ store }}</a>)</li>
            {% endfor %}
        </ul>        
    {% else %}
        <p>Todos los equipos están disponibles</p>
    {% endif %}
</div>
    
{% endblock %}

django/templates/manager/store_has_product_entity_edit.html
{% extends "manager/base.html" %}

{% block title %}Editar entrada de producto - {{ site_name }}{% endblock %}

{% block manager_content %}

<h2><a href="{{ shpe.url }}">{{ shpe }}</a></h2>
<h4>
    Tienda: {{ shpe.store }}
</h4>
<h4>
    Precio: {{ shpe.pretty_price }}
</h4>
<h4>
    Disponibilidad: {% if shpe.is_available %} Disponible {% else %} No disponible {% endif %} / Visibilidad: {% if shpe.is_hidden %} No visible {% else %} Visible {% endif %}
</h4>

<form method="post" action="">
    <select id="id_product" name="product">
        <option value="">---------</option>
        {% for option in options %}
            <option value="{{ option.id }}"
            {% ifequal shpe.shp.product.id option.id %}
             selected="selected" 
            {% endifequal %}
            >{{ option }}</option>
        {% endfor %}
    </select>
    
    <a id="product_link" href="#">Ver producto</a>
    
    <p>
        {% if shpe.is_hidden %}
        <a href="{% url solonotebooks.cotizador.views_manager.storehasproductentity_show shpe.id %}">Hacer visible</a>
        {% else %}
        <a href="{% url solonotebooks.cotizador.views_manager.storehasproductentity_hide shpe.id %}">Hacer no visible</a>
        {% endif %}
        |
        <a href="{% url solonotebooks.cotizador.views_manager.storehasproductentity_refresh_price shpe.id %}">Refrescar precio y disponibilidad</a>
    </p>
    <p>
        <input type="submit" value="Guardar" />
    </p>
</form>

{% endblock %}